### ISSUE TITLE
[Manjaro] [Bug] Gives errors when run from a Terminal

### ISSUE THREAD

**Issue by HoloKola** [trinkey/scuffedttt#1]
The script doesn't run on my system. I'm running Manjaro Linux version 21.2.4.

Here is the output:
`/home/holokola/Downloads/TicTacToe.py: line 2: $'\r': command not found
/home/holokola/Downloads/TicTacToe.py: line 3: win: command not found
/home/holokola/Downloads/TicTacToe.py: line 4: pls: command not found
/home/holokola/Downloads/TicTacToe.py: line 5: ais: command not found
/home/holokola/Downloads/TicTacToe.py: line 6: a: command not found
/home/holokola/Downloads/TicTacToe.py: line 7: b: command not found
/home/holokola/Downloads/TicTacToe.py: line 8: c: command not found
/home/holokola/Downloads/TicTacToe.py: line 9: av: command not found
/home/holokola/Downloads/TicTacToe.py: line 10: AISpecialCase: command not found
/home/holokola/Downloads/TicTacToe.py: line 11: $'\r': command not found
/home/holokola/Downloads/TicTacToe.py: line 12: syntax error near unexpected token 0,1'
home/holokola/Downloads/TicTacToe.py: line 12: if random.randint(0,1) == 1:`

Here is my neofetch:
![image](https://user-images.githubusercontent.com/84939011/163893788-420a0d9f-e31e-4481-8f56-64b7e9d48565.png)

**Comment by trinkey** [comment]
![cropped](https://user-images.githubusercontent.com/97406176/164110979-8b24a295-28cf-44de-9d0b-e598acd97186.jpg)
I'm using Kali, and python 3.9.10 and it works perfectly fine. (I am using 3.10.4 on my Windows 11 device and that also works perfectly fine.) Unsure why it didn't work for you.
